<?php

class Rectangle {
    protected $height;
    protected $width;


    public function getHeight()
    {
        return $this->height;
    }


    public function getWidth()
    {
        return $this->width;
    }


    public function setHeight($height): void
    {
        $this->height = $height;
    }


    public function setWidth($width): void
    {
        $this->width = $width;
    }

    public function area() {
        return $this->width * $this->height;
    }

}

class Square extends Rectangle {
     public function setHeight($height): void
     {
         parent::setHeight($height); // TODO: Change the autogenerated stub
         parent::setWidth($height); // TODO: Change the autogenerated stub
     }

          public function setWidth($height): void
     {
         parent::setHeight($height); // TODO: Change the autogenerated stub
         parent::setWidth($height); // TODO: Change the autogenerated stub
     }

}

$rec = new Square();
$rec->setWidth(5);
$rec->setHeight(4);
echo $rec->area();